### ISSUE TITLE
Blank at start, blank and empty windows, cannot connect.

### ISSUE THREAD

**Issue by tr1p0p** [sharkwouter/minigalaxy#584]
So, just download Minigalaxy on fedora 38 on a X.org session.

And i'm quite disappointed that the program just... don't work and show blank windows to connect to GOG. So nothing work, and i cannot do anything.

Here the result :  
![image](https://github.com/sharkwouter/minigalaxy/assets/37407065/1b6cc957-651f-426d-9c56-56c04408f904)

I just installed minigalaxy with repo and launch it, that's all what i do.

**Comment by tim77** [comment]
Works for me on Fedora 39/GNOME/Wayland/Mesa drivers/RPM version of Minigalaxy. Please provide more information:
- Flathub or RPM build of Minigalaxy?
- GPU drivers
- Desktop Environment

![Fedora-39_03_10_2023_12_11_09](https://github.com/sharkwouter/minigalaxy/assets/5614476/f2aaecb1-65f3-4e6f-962d-ab91752f5c5d)

**Comment by sharkwouter** [comment]
Thanks for reporting this. Sorry for the late reply. I'd say the best way to get figure out what's going on here would be to run minigalaxy from a terminal and copy the output like Tim mentioned. Then we can look into this further.

**Comment by tr1p0p** [comment]
Hi !
So. Hum No info on terminal when i launch the program. Also coredumpctl list also don't really show nothing at the launch of the program.

Also i will precise more my environment . I'm on a GTX 970 (Yeah, nvidia.. I think it's certainly the nvidia drivers that do this) so that's why i'm on X.org, because wayland lack some features for me (like, night mode). Also i got a AMD Ryzen 5600. And it's the rpm build.

**Comment by tim77** [comment]
I also on Nvidia. But in some rare cases i could reproduce this on Fedora 39 in clear VM and free GPU drivers. Problem with webkitgtk process crashing. When i will have more time i'll try dig more, but definitely help wanted here.

**Comment by sharkwouter** [comment]
A workaround that was mentioned by the reporter on Discord was to run Minigalaxy like this:
```
WEBKIT_DISABLE_COMPOSITING_MODE=1 minigalaxy
```

After logging in once, doing so again should not be needed for a while, so this does not have to be repeated often.

**Comment by lietuv1s** [comment]
Same blank library window (sign in window is fine) with second drive mounted on "/home/me/Games" and (game) "install_dir" pointing to it.
Somewhat fixed after editing "install_dir" to point "/home/me" only.
![paveikslas](https://github.com/sharkwouter/minigalaxy/assets/29211156/1eefd326-5740-4d96-98ab-d1926e9d8d5a)

**Comment by solt87** [comment]
I have the same issue. Since the issue first appeared to me when I was using a custom, stripped-down kernel, I thought it was caused by a missing kernel module, but now that I'm running a distro-provided kernel again (with which I had no problems before), the issue persists, so it must be something else.

```
System:
  Kernel: 5.15.0-89-generic arch: x86_64 bits: 64 Desktop: Xfce v: 4.18.1
    Distro: Linux Mint 21.2 Victoria
Graphics:
  Device-1: NVIDIA GK106 [GeForce GTX 650 Ti] driver: nvidia v: 470.223.02
  Display: x11 server: X.Org v: 1.21.1.4 with: Xwayland v: 22.1.1 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6.0 vendor: nvidia v: 470.223.02 renderer: NVIDIA
    GeForce GTX 650 Ti/PCIe/SSE2
```
By the way, the workaround works for me, so thank you for that.
